spring:
  profiles:
    active:
      - db
  datasource:
    url: jdbc:mysql://localhost:3307/selabdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  hibernate:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect